<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'CommandParser' => 'parser/CommandParser.php',
    'Job' => 'shell/Job.php',
    'JobControl' => 'shell/JobControl.php',
    'Process' => 'shell/Process.php',
    'Shell' => 'shell/Shell.php',
  ),
  'function' => array(),
  'xmap' => array(
    'Job' => 'Phobject',
    'Process' => 'Phobject',
    'Shell' => 'Phobject',
  ),
));
